name: CI/CD Pipeline

# Trigger the workflow on push or pull request events to the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js (or specify your environment)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or specify your desired version

      - name: Install dependencies
        run: npm install  # For Node.js, adjust if using another language or stack
      
      - name: Run tests
        run: npm test  # Replace with your test command
      
      - name: Build project
        run: npm run build  # Replace with your build command, if applicable

  # Deploy job
  deploy:
    needs: build  # Ensures the deploy job runs only if the build is successful
    runs-on: ubuntu-latest
    environment: production  # Specify the environment, optional but useful for environments like production, staging, etc.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH for deployment (Optional, if using SSH)
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your private key in GitHub Secrets

      - name: Deploy to server (Example using SCP or SSH)
        run: |
          echo "Deploying to production server..."
          # Replace the following with your deploy commands:
          scp -r ./build user@your-server:/path/to/deploy/directory
          
      - name: Notify deployment (optional)
        run: echo "Deployment to production complete!"

  # Optional: Rollback or additional jobs like staging deployment, notifications, etc.
